INSERT INTO items (brand, model, internal_memory, RAM, color,
                   OS, image, item_sales_information_id, version)
VALUES ('APPLE','iPhone 13', 'GB_256','GB_8','Black',
        'IOS','image_url.jpg',1,1),
('SAMSUNG','Galaxy S21', 'GB_128','GB_12','White',
        'ANDROID','image_url2.jpg',2,1),
    ('GOOGLE',         
    'Pixel 6',             
    'GB_128',            
    'GB_8',              
    'Blue1',              
    'ANDROID',          
    'image_url3.jpg',         
    3,                
    1                
    ),
(
    'XIAOMI',         
    'Mi 11',               
    'GB_256',            
    'GB_8',              
    'Blue2',              
    'ANDROID',          
    'image_mi11.jpg',         
    4,                
    1                
),
    (
    'HONOR',         
    'Honor 50',            
    'GB_128',            
    'GB_6',              
    'Green',             
    'ANDROID',          
    'image_honor50.jpg',          
    5,                
    1                
    ),
    (
    'HUAWEI',         
    'P40 Pro',             
    'GB_512',                
    'GB_12',                 
    'Silver',            
    'ANDROID',          
    'image_p40pro.jpg',          
    6,                
    1                
    ),
    (
    'GOOGLE',         
    'Pixel 5',             
    'GB_128',            
    'GB_8',              
    'Black',             
    'ANDROID',          
    'image_pixel5.jpg',          
    7,                
    1                
    ),
    (
    'ONEPLUS',        
    'OnePlus 9',           
    'GB_256',            
    'GB_12',                 
    'Blue3',              
    'ANDROID',          
    'image_oneplus9.jpg',          
    8,                
    1                
    ),
    (
    'OPPO',                 
    'Find X3',             
    'GB_512',                
    'GB_12',                 
    'White',             
    'ANDROID',          
    'image_findx3.jpg',
    9,                
    1                
    ),
    (
    'POCO',          
    'M3',                  
    'GB_64',             
    'GB_4',             
    'Yellow',            
    'ANDROID',          
    'image_pocom3.jpg',
    10,
    1                
    ),
    (
    'REALME',
    'GT',
    'GB_128',
    'GB_8',
    'Black',
    'ANDROID',
    'image_gt.jpg',
    11,
    1
    ),
    (
    'TECNO',
    'Camon 16',
    'GB_128',
    'GB_6',
    'Purple',
    'ANDROID',
    'image_camon16.jpg',
    12,
    1
    ),
    (
    'VIVO',
    'V21',
    'GB_256',
    'GB_8',
    'Blue4',
    'ANDROID',
    'image_v21.jpg',
    13,
    1
    ),
    ('APPLE', 'iPhone 13', 'GB_256', 'GB_4', 'Black', 'IOS', 'image_iphone13.jpg', 14, 1),
    ('APPLE', 'iPhone 13 Pro', 'GB_512', 'GB_6', 'Silver', 'IOS', 'image_iphone13pro.jpg', 15, 1),
    ('SAMSUNG', 'Galaxy S21', 'GB_128', 'GB_8', 'White', 'ANDROID', 'image_galaxys21.jpg', 16, 1),
    ('SAMSUNG', 'Galaxy Note 20', 'GB_256', 'GB_12', 'Gray', 'ANDROID', 'image_note20.jpg', 17, 1),
    ('XIAOMI', 'Mi 11', 'GB_256', 'GB_8', 'Blue5', 'ANDROID', 'image_mi11.jpg', 18, 1),
    ('XIAOMI', 'Redmi Note 10', 'GB_128', 'GB_6', 'Green', 'ANDROID', 'image_note10.jpg', 19, 1);

INSERT INTO item_sales_information (price, currency, quantity)
VALUES (1000, '₸', 100),
       (2000, '₸', 200),
       (3000, '$', 300),
       (4000, '$', 400),
       (5000, '$', 500),
       (6000, '₸', 600),
       (7000, '₸', 700),
       (8000, '₴', 800),
       (9000, '₴', 900),
       (10000, '₴', 200),
       (11000, '₸', 200),
       (12000, '$', 200),
       (13000, '$', 200),
       (14000, '$', 200),
       (16000, '₽', 200),
       (17000, '₸', 200),
       (18000, '₽', 200),
       (19000, '₽', 200),
       (20000, '₴', 200);

C